// set funct interrupts  
SPIM.CHIRP_FUNC_INT_ENABLE.CHIRP_AAFC_START_INT_EN=1;
SPIM.CHIRP_FUNC_INT_ENABLE.CHIRP_AAFC_END_INT_EN=1;
SPIM.CHIRP_FUNC_INT_ENABLE.CHIRP_VTUNE_LOW_INT_EN=1;
SPIM.CHIRP_FUNC_INT_ENABLE.CHIRP_VTUNE_HIGH_INT_EN=1;
