// set funct interrupts  
SPIM.TX_FUNC_INT_ENABLE.TX1_PR_CALIB_START_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX1_PR_CALIB_END_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX2_PR_CALIB_START_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX2_PR_CALIB_END_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX3_PR_CALIB_START_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX3_PR_CALIB_END_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX4_PR_CALIB_START_INT_EN=1;
SPIM.TX_FUNC_INT_ENABLE.TX4_PR_CALIB_END_INT_EN=1;
