//Disable BG 

ATB.PVT_REF_GEN_BIST_0.ENA_BG= 0;

//DISABLE BG Buffer

ATB.PVT_REF_GEN_BIST_0.BYPASS_BG_RC=0; 
ATB.PVT_REF_GEN_BIST_0.ENA_BG_BUF=0; 



// ATB1,2 ADC disables

ATB.PVT_REF_GEN_BIST_1.ENA_ADC_ATB1=0;
ATB.PVT_REF_GEN_BIST_1.ENA_ADC_ATB1=0;
