%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\nxf44611\Desktop\TX_Power.xlsx
%    Worksheet: Tabelle1
%
% Auto-generated by MATLAB on 01-Jun-2022 13:42:16

function TXPower=readTxOutputPowerParam(filename)

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range60
opts.Sheet = "Tabelle1";
opts.DataRange = "A2:J85";

% Specify column names and types
opts.VariableNames = ["center_freq", "tx_power", "tx1_enable", "tx2_enable", "tx3_enable", "tx4_enable", "tx1_enable_1", "tx2_enable_1", "tx3_enable_1", "tx4_enable_1"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["center_freq", "tx_power", "tx1_enable", "tx2_enable", "tx3_enable", "tx4_enable", "tx1_enable_1", "tx2_enable_1", "tx3_enable_1", "tx4_enable_1"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["center_freq", "tx_power", "tx1_enable", "tx2_enable", "tx3_enable", "tx4_enable", "tx1_enable_1", "tx2_enable_1", "tx3_enable_1", "tx4_enable_1"], "EmptyFieldRule", "auto");

% Import the data
TXPower = readtable(filename, opts, "UseExcel", false);

%% Convert to output type
TXPower = table2cell(TXPower);
numIdx = cellfun(@(x) ~isnan(str2double(x)), TXPower);
TXPower(numIdx) = cellfun(@(x) {str2double(x)}, TXPower(numIdx));

%% Clear temporary variables
clear opts