/* idaSTRX_chirppll_cfg_SgdMod.bf */

CHIRPPLL.SGD_MOD_CTRL.LPF_ENABLE=0;
CHIRPPLL.SGD_MOD_CTRL.LPF_ORDER=1; // 3rd order
CHIRPPLL.SGD_MOD_CTRL.ORDER=1;
CHIRPPLL.SGD_MOD_CTRL.LIN_INT_OFF=0;
CHIRPPLL.SGD_MOD_CTRL.DITHER_ENABLE=1;
CHIRPPLL.SGD_MOD_CTRL.DITHER_AUTO_OFF=0;
CHIRPPLL.SGD_MOD_CTRL.DITHER_AMP=1000;
CHIRPPLL.SPARE_CTL.DIG_SPARE=1; // High pass dithering filter
CHIRPPLL.DIVIDE_FORCE_CTL.FORCE_DIVIDER=1;
CHIRPPLL.DIVIDE_FORCE_CTL.DIV_FORCE=29;
