/* idaSTRX_chirppll_cfg_StaticPwrCtrl.bf */

//TIMING_ENGINE.DYNAMIC_POWER_CONTROL_ENABLE.write(status, 32'h00FFFFFF);
TIMING_ENGINE.POWER_CONTROL_ENABLE.CHIRP_PWR_CTRL=1;
TIMING_ENGINE.DYNAMIC_POWER_CONTROL_ENABLE.CHIRP_DY_PWR_CTRL=0;


