
/* idaSTRX_chirppll_cfg_sel_VCO_mode4G.bf */
//9) Select VCO 4G
CHIRPPLL.P0_ANA_VCO_CTL1_VCO_SEL		= 1; // Selectt VCO default: 1 --> 1G, 0 --> 4G
CHIRPPLL.ANA_RMSDET_CTL.RMS_SEL			= 2; // Selects RMS DET default: 1 --> 1G, 2 --> 4G
//10) Load all the profiles
// TO check:
TIMING_ENGINE.PROFILE_SEL_CW_MODE.USE_PROFILE_FOR_CW_MODE	=1;
TIMING_ENGINE.PROFILE_SEL_CW_MODE.EN_PROFILE_FOR_CW_MODE	=1;
TIMING_ENGINE.PROFILE_SEL_CW_MODE.SW_LD_PROFILE_FOR_CW_MODE	=1;