TIMING_ENGINE.TX_PR_DELAY_CTL.PR_CALIB_ENABLE=0x1; # Control to enable PR Calibration
TIMING_ENGINE.TX_PR_CALIBRATION_SW_CTL.PR_CALIBRATION_TIMEOUT_COUNTER=0xbb80;#1.2 ms # PR Calibration Timeout Counter in CW mode
TIMING_ENGINE.TX_PR_CALIBRATION_SW_CTL.START_TX_PR_CALIBRATION=0x1; # Trigger for PR Calib in CW mode

