# Control Configures the initial phase of TX
TIMING_ENGINE.TX_PR_12_DDMA_INIT_PHASE.TX1_PR_DDMA_INIT_PHASE=0x000;#0 degree 
TIMING_ENGINE.TX_PR_12_DDMA_INIT_PHASE.TX2_PR_DDMA_INIT_PHASE=0x000;#0 degree
TIMING_ENGINE.TX_PR_34_DDMA_INIT_PHASE.TX3_PR_DDMA_INIT_PHASE=0x000;#0 degree
TIMING_ENGINE.TX_PR_34_DDMA_INIT_PHASE.TX4_PR_DDMA_INIT_PHASE=0x000;#0 degree

