# Profile Based TX PR Phase Change Control (Profile0)
TIMING_ENGINE.PR_PHASE_CTL_PROF0.TX1_PR_PHASE_CONTROL_PROFILE0=0x10; # 45 degrees 
TIMING_ENGINE.PR_PHASE_CTL_PROF0.TX2_PR_PHASE_CONTROL_PROFILE0=0x10; # 45 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF0.TX3_PR_PHASE_CONTROL_PROFILE0=0x10; # 45 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF0.TX4_PR_PHASE_CONTROL_PROFILE0=0x10; # 45 degrees

