# Control configures the step phase change of TX
# Incrementing Phase change is configured for TX1 & TX2
TIMING_ENGINE.TX_PR_12_DDMA_STEP_PHASE.TX1_PR_DDMA_STEP_PHASE=0x080;#45 deg
TIMING_ENGINE.TX_PR_12_DDMA_STEP_PHASE.TX2_PR_DDMA_STEP_PHASE=0x100;#90 deg
# Decrementing Phase change is configured for TX3 & TX4
TIMING_ENGINE.TX_PR_34_DDMA_STEP_PHASE.TX3_PR_DDMA_STEP_PHASE=0x380;#-45 deg  
TIMING_ENGINE.TX_PR_34_DDMA_STEP_PHASE.TX4_PR_DDMA_STEP_PHASE=0x300;#-90 deg

