# Profile Based TX PR Phase Change Control (Profile2)
TIMING_ENGINE.PR_PHASE_CTL_PROF2.TX1_PR_PHASE_CONTROL_PROFILE2=0x30; # 135 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF2.TX2_PR_PHASE_CONTROL_PROFILE2=0x30; # 135 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF2.TX3_PR_PHASE_CONTROL_PROFILE2=0x30; # 135 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF2.TX4_PR_PHASE_CONTROL_PROFILE2=0x30; # 135 degrees



