# Profile Based TX PR Phase Change Control (Profile1)
TIMING_ENGINE.PR_PHASE_CTL_PROF1.TX1_PR_PHASE_CONTROL_PROFILE1=0x20; # 90 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF1.TX2_PR_PHASE_CONTROL_PROFILE1=0x20; # 90 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF1.TX3_PR_PHASE_CONTROL_PROFILE1=0x20; # 90 degrees
TIMING_ENGINE.PR_PHASE_CTL_PROF1.TX4_PR_PHASE_CONTROL_PROFILE1=0x20; # 90 degrees







