%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\STRX\RFE_Integration_Test\MCGEN_check.xlsx
%    Worksheet: Tabelle1
%
% Auto-generated by MATLAB on 24-Jun-2022 10:45:11

function MCGENcheck=read_MCGEN_check_Input(filename)

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Tabelle1";
opts.DataRange = "A2:G7";

% Specify column names and types
opts.VariableNames = ["freq", "PLL_loop_filter_bw", "tx_power", "TX1", "TX2", "TX3", "TX4"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["freq", "PLL_loop_filter_bw", "tx_power", "TX1", "TX2", "TX3", "TX4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["freq", "PLL_loop_filter_bw", "tx_power", "TX1", "TX2", "TX3", "TX4"], "EmptyFieldRule", "auto");

% Import the data
MCGENcheck = readtable(filename, opts, "UseExcel", false);

%% Convert to output type
MCGENcheck = table2cell(MCGENcheck);
numIdx = cellfun(@(x) ~isnan(str2double(x)), MCGENcheck);
MCGENcheck(numIdx) = cellfun(@(x) {str2double(x)}, MCGENcheck(numIdx));

%% Clear temporary variables
clear opts
