%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: M:\15_STRX\8_Software\RFE_Integration_Test\RX_attenuation_over_distance.xlsx
%    Worksheet: Tabelle1
%
% Auto-generated by MATLAB on 27-Jun-2022 14:44:09

function RXattenuationoverdistance=read_input_RX_attenuation_over_distance(filename)
%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Tabelle1";
opts.DataRange = "A2:J6";

% Specify column names and types
opts.VariableNames = ["center_freq", "tx_power", "tx1_enable", "tx2_enable", "tx3_enable", "tx4_enable", "tx1_enable_1", "tx2_enable_1", "tx3_enable_1", "tx4_enable_1"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["center_freq", "tx_power", "tx1_enable", "tx2_enable", "tx3_enable", "tx4_enable", "tx1_enable_1", "tx2_enable_1", "tx3_enable_1", "tx4_enable_1"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["center_freq", "tx_power", "tx1_enable", "tx2_enable", "tx3_enable", "tx4_enable", "tx1_enable_1", "tx2_enable_1", "tx3_enable_1", "tx4_enable_1"], "EmptyFieldRule", "auto");

% Import the data
RXattenuationoverdistance = readtable(filename, opts, "UseExcel", false);

%% Convert to output type
RXattenuationoverdistance = table2cell(RXattenuationoverdistance);
numIdx = cellfun(@(x) ~isnan(str2double(x)), RXattenuationoverdistance);
RXattenuationoverdistance(numIdx) = cellfun(@(x) {str2double(x)}, RXattenuationoverdistance(numIdx));

%% Clear temporary variables
clear opts